/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formtk;

import java.beans.Statement;
import java.io.File;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import formtk.KoneksiDB;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author ASUS
 */
public class Form_DataHasilSAW extends javax.swing.JInternalFrame {
        /**
     * Creates new form Form_Data_Barang
     */
    
       
    public Form_DataHasilSAW() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).setNorthPane(null);
        ViewData();
        LebarKolom();
        ViewData2();
        LebarKolom2();
        Locale locale = new Locale("id","ID");
        Locale.setDefault(locale);
    }
    
    private void LebarKolom(){
        TableColumn column;
        tbdatapelanggan.getColumnModel().getColumn(0).setPreferredWidth(100);
        tbdatapelanggan.getColumnModel().getColumn(1).setPreferredWidth(100);
        tbdatapelanggan.getColumnModel().getColumn(2).setPreferredWidth(100); 
        tbdatapelanggan.getColumnModel().getColumn(3).setPreferredWidth(100); 
        tbdatapelanggan.getColumnModel().getColumn(4).setPreferredWidth(100);
        tbdatapelanggan.getColumnModel().getColumn(5).setPreferredWidth(100); 
        tbdatapelanggan.getColumnModel().getColumn(6).setPreferredWidth(100); 
    }
    
    private void LebarKolom2(){
        TableColumn column;
        tbdatanilai.getColumnModel().getColumn(0).setPreferredWidth(100);
        tbdatanilai.getColumnModel().getColumn(1).setPreferredWidth(100);
        tbdatanilai.getColumnModel().getColumn(2).setPreferredWidth(100); 
        tbdatanilai.getColumnModel().getColumn(3).setPreferredWidth(100); 
        tbdatanilai.getColumnModel().getColumn(4).setPreferredWidth(100);
        tbdatanilai.getColumnModel().getColumn(5).setPreferredWidth(100); 
         tbdatanilai.getColumnModel().getColumn(6).setPreferredWidth(100); 
    }
    
    private void ViewData(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("ID Nilai Kriteria");
        tbl.addColumn("ID Siswa");
        tbl.addColumn("Nama");
        tbl.addColumn("Absensi");
        tbl.addColumn("Nilai Akademik");
        tbl.addColumn("Nilai Keterampilan");
        tbl.addColumn("Indisipliner");
        tbdatapelanggan.setModel(tbl);
        LebarKolom();
        try {
           com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement)KoneksiDB.getConnection().createStatement();
           ResultSet rs = statement.executeQuery("select * from nilaikriteria");
           while(rs.next()){
               tbl.addRow(new Object[]{
                   rs.getString("IDNilaiKriteria"),
                   rs.getString("IDmobil"),
                   rs.getString("merk"),
                   rs.getString("jarak"),
                   rs.getString("harga"),
                   rs.getString("usiamobil"),
                   rs.getString("bbm"),
               });
               tbdatapelanggan.setModel(tbl);
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Gagal");
        }
    }
    
    private void ViewData2(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("ID Siswa");
        tbl.addColumn("Nama");
        tbl.addColumn("Absensi");
        tbl.addColumn("Nilai Akademik");
        tbl.addColumn("Nilai Keterampilan");
        tbl.addColumn("Indisipliner");
        tbl.addColumn("Preferensi");
        tbdatanilai.setModel(tbl);
        LebarKolom2();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnprint = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdatapelanggan = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnkeluar1 = new javax.swing.JButton();
        btnproses = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbdatanilai = new javax.swing.JTable();
        btnproses1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbperingkat = new javax.swing.JTable();
        btnbobot = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtusia = new javax.swing.JTextField();
        txtpdt = new javax.swing.JTextField();
        txtrwt = new javax.swing.JTextField();
        txttg = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        btnprint.setBackground(new java.awt.Color(102, 102, 102));
        btnprint.setForeground(new java.awt.Color(255, 255, 255));
        btnprint.setText("Cetak");
        btnprint.setPreferredSize(new java.awt.Dimension(109, 29));
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        tbdatapelanggan.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        tbdatapelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "null", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(tbdatapelanggan);
        if (tbdatapelanggan.getColumnModel().getColumnCount() > 0) {
            tbdatapelanggan.getColumnModel().getColumn(3).setHeaderValue("null");
        }

        jLabel3.setBackground(new java.awt.Color(255, 0, 0));
        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("Data Hasil Kelayakan Berdasarkan Peringkat");

        jLabel4.setText("Form ini dugunakan untuk melihat hasil kelayakan");

        btnkeluar1.setBackground(new java.awt.Color(102, 102, 102));
        btnkeluar1.setForeground(new java.awt.Color(255, 255, 255));
        btnkeluar1.setText("Keluar");
        btnkeluar1.setPreferredSize(new java.awt.Dimension(109, 29));
        btnkeluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluar1ActionPerformed(evt);
            }
        });

        btnproses.setBackground(new java.awt.Color(102, 102, 102));
        btnproses.setForeground(new java.awt.Color(255, 255, 255));
        btnproses.setText("Proses Normalisasi dan Preferensi");
        btnproses.setPreferredSize(new java.awt.Dimension(109, 29));
        btnproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprosesActionPerformed(evt);
            }
        });

        tbdatanilai.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        tbdatanilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "null", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane2.setViewportView(tbdatanilai);
        if (tbdatanilai.getColumnModel().getColumnCount() > 0) {
            tbdatanilai.getColumnModel().getColumn(3).setHeaderValue("null");
        }

        btnproses1.setBackground(new java.awt.Color(102, 102, 102));
        btnproses1.setForeground(new java.awt.Color(255, 255, 255));
        btnproses1.setText("Peringkat");
        btnproses1.setPreferredSize(new java.awt.Dimension(109, 29));
        btnproses1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproses1ActionPerformed(evt);
            }
        });

        tbperingkat.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        tbperingkat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane3.setViewportView(tbperingkat);

        btnbobot.setBackground(new java.awt.Color(102, 102, 102));
        btnbobot.setForeground(new java.awt.Color(255, 255, 255));
        btnbobot.setText("Tampilkan Nilai Bobot Kriteria");
        btnbobot.setPreferredSize(new java.awt.Dimension(109, 29));
        btnbobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbobotActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Absensi");

        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("Nilai Akademik");

        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setText("Nikai Kedisiplinan");

        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("Indisipliner");

        btnsimpan.setBackground(new java.awt.Color(102, 102, 102));
        btnsimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnsimpan.setText("Simpan");
        btnsimpan.setPreferredSize(new java.awt.Dimension(109, 29));
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtusia)
                                    .addComponent(txtpdt)
                                    .addComponent(txtrwt)
                                    .addComponent(txttg)))
                            .addComponent(btnbobot, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnproses, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnproses1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnprint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnkeluar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 191, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnproses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnbobot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnproses1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnprint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnkeluar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtusia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtpdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(txtrwt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txttg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(310, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
         try {
            String file = "src/formtk/ranking.jasper";
            HashMap parameter = new HashMap();
            File reportFile = new File(file);
            JasperReport jsr = (JasperReport) JRLoader.loadObject(null, reportFile);
            JasperPrint jsp = JasperFillManager.fillReport(jsr, parameter, KoneksiDB.getConnection());
            JasperViewer.viewReport(jsp,false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnprintActionPerformed

    private void btnkeluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnkeluar1ActionPerformed

    private void btnprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprosesActionPerformed
        // TODO add your handling code here:
        Connection connection = KoneksiDB.getConnection();
        
        double usiat = Double.parseDouble(txtusia.getText());
        double pendapatant = Double.parseDouble(txtpdt.getText());
        double riwayatt = Double.parseDouble(txtrwt.getText());
        double tanggungant = Double.parseDouble(txttg.getText());

        if (connection != null) {
            try {
                String maxSql = "SELECT MIN(jarak) AS min_jarak, MAX(harga) AS max_harga, \n" +
"MIN(usiamobil) AS min_usiamobil, MIN(bbm) AS min_bbm FROM nilaikriteria";
                PreparedStatement maxStatement = connection.prepareStatement(maxSql);
                ResultSet maxResultSet = maxStatement.executeQuery();
                
                double minUsia = 0;
                double maxPendapatan = 0;
                double maxRKredit = 0;
                double minTanggungan = 0;
                if (maxResultSet.next()) {
                    minUsia = maxResultSet.getDouble("min_jarak");
                    maxPendapatan = maxResultSet.getDouble("max_harga");
                    maxRKredit = maxResultSet.getDouble("min_usiamobil");
                    minTanggungan = maxResultSet.getDouble("min_bbm");
                }

                String selectSql = "SELECT IDmobil, merk, jarak, harga, usiamobil, bbm FROM nilaikriteria";
                PreparedStatement selectStatement = connection.prepareStatement(selectSql);
                ResultSet selectResultSet = selectStatement.executeQuery();
                
                String[] columnNames = {"ID ", "Nama", "Absensi", "Nilai Akademik","Nilai Keterampilan","Indisipliner","Preferensi"};
                DefaultTableModel model = new DefaultTableModel(columnNames, 0);
                
                while (selectResultSet.next()) {
                    String id = selectResultSet.getString("IDmobil");
                    String nama = selectResultSet.getString("merk");
                    double usia = selectResultSet.getDouble("jarak");
                    double pendapatan = selectResultSet.getDouble("harga");
                    double RiwKredit = selectResultSet.getDouble("usiamobil");
                    double JmlTanggungan = selectResultSet.getDouble("bbm");

                    // Bagi harga dengan nilai maksimum
                    double normalizedUsia = minUsia / usia;
                    double normalizedPendapatan = pendapatan / maxPendapatan;
                    double normalizedRKredit = RiwKredit / maxRKredit;
                    double normalizedJmlTanggungan = minTanggungan / JmlTanggungan;
                    
                    if (Double.isNaN(normalizedJmlTanggungan)) {
                            normalizedJmlTanggungan = 0; 
                    }
                    
                    //Nilai Preferensi
                    
                    double preferensi = (normalizedUsia*(usiat/100))+(normalizedPendapatan*(pendapatant)/100)+(normalizedRKredit*(riwayatt/100))+(normalizedJmlTanggungan*(tanggungant/100));
                    
                    String formattedUsia = String.format("%.3f", normalizedUsia);
                    String formattedPendapatan = String.format("%.3f", normalizedPendapatan);
                    String formattedRKredit = String.format("%.3f", normalizedRKredit);
                    String formattedJmlTanggungan = String.format("%.3f", normalizedJmlTanggungan);
                    String formattedPreferensi = String.format("%.3f", preferensi);

                    Object[] row = {id, nama, formattedUsia, formattedPendapatan, formattedRKredit, formattedJmlTanggungan,formattedPreferensi};
                    model.addRow(row);
                    tbdatanilai.setModel(model);
                }

                // Menutup resources
                maxResultSet.close();
                maxStatement.close();
                selectResultSet.close();
                selectStatement.close();

            } catch (SQLException e) {
                e.printStackTrace();
            } finally {
                try {
                    // Menutup koneksi
                    if (connection != null) {
                        connection.close();
                    }
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_btnprosesActionPerformed

    private void btnproses1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproses1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel(new Object[]{"ID ","Nama ","Preferensi"}, 0);
        int rowCount = tbdatanilai.getRowCount();
        List<Object[]> hasilpreferensi = new ArrayList<>();
        
        /*for (int i = 0; i < rowCount; i++) {
            Object idpelanggan = tbdatanilai.getValueAt(i, 0);
            Object nama = tbdatanilai.getValueAt(i, 1);
            Object preferensi = tbdatanilai.getValueAt(i, 6);
            model.addRow(new Object[]{idpelanggan,nama,preferensi});
            }*/
        
        for (int i = 0; i < rowCount; i++) {
                    Object[] row = new Object[3];
                    row[0] = tbdatanilai.getValueAt(i, 0); // ID
                    row[1] = tbdatanilai.getValueAt(i, 1); // Nama
                    row[2] = tbdatanilai.getValueAt(i, 6); // Preferensi
                    hasilpreferensi.add(row);
                }
        
        
         hasilpreferensi.sort(new Comparator<Object[]>() {
                    @Override
                    public int compare(Object[] row1, Object[] row2) {
                        try {
                            NumberFormat format = NumberFormat.getInstance(Locale.getDefault());
                            Number pr1 = format.parse((String) row1[2]);
                            Number pr2 = format.parse((String) row2[2]);
                            //Double pr1 = Double.parseDouble((String) row1[2]);
                            //Double pr2 = Double.parseDouble((String) row2[2]);
                            return Double.compare(pr2.doubleValue(), pr1.doubleValue());
                        } catch (ParseException ex) {
                            Logger.getLogger(Form_DataHasilSAW.class.getName()).log(Level.SEVERE, null, ex);
                            return 0;
                        }
                    }
                });
         
         
         for (Object[] row : hasilpreferensi) {
                    model.addRow(row);
                    
                }
        
        
        tbperingkat.setModel(model);
    }//GEN-LAST:event_btnproses1ActionPerformed

    private void btnbobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbobotActionPerformed
        try {
            // TODO add your handling code here:
            com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement)KoneksiDB.getConnection().createStatement();
            ResultSet rs = statement.executeQuery("SELECT bobot FROM kriteria LIMIT 4");
            
            if (rs.next()) txtusia.setText(String.valueOf(rs.getInt("bobot")));
            if (rs.next()) txtpdt.setText(String.valueOf(rs.getInt("bobot")));
            if (rs.next()) txtrwt.setText(String.valueOf(rs.getInt("bobot")));
            if (rs.next()) txttg.setText(String.valueOf(rs.getInt("bobot")));

        }catch (SQLException e) {
                e.printStackTrace();
            } 
    }//GEN-LAST:event_btnbobotActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        PreparedStatement deleteStmt = null;
        PreparedStatement insertStmt = null;

        try {
            // 1. Membuat koneksi ke database
            String url = "jdbc:mysql://localhost:3306/mobil";
            String user = "root";
            String password = "";
            conn = DriverManager.getConnection(url, user, password);

            // 2. Menghapus semua data lama dari tabel
            String deleteSQL = "DELETE FROM hasilsaw";
            deleteStmt = conn.prepareStatement(deleteSQL);
            deleteStmt.executeUpdate();

            // 3. Menyiapkan query untuk memasukkan data baru
            String insertSQL = "INSERT INTO hasilsaw (IDmobil,merk,SkorTotal) VALUES (?, ?, ?)";
            insertStmt = conn.prepareStatement(insertSQL);

            // 4. Iterasi melalui data di JTable dan masukkan ke database
            for (int i = 0; i < tbperingkat.getRowCount(); i++) {
                
                insertStmt.setString(1, (String) tbperingkat.getValueAt(i, 0)); 
                insertStmt.setString(2, (String) tbperingkat.getValueAt(i, 1)); 
                insertStmt.setString(3, (String) tbperingkat.getValueAt(i, 2)); 
                insertStmt.executeUpdate();
            }

            JOptionPane.showMessageDialog(null, "Data Berhasil di Simpan");
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Tidak  Tersimpan");
        } finally {
            try {
                if (deleteStmt != null) deleteStmt.close();
                if (insertStmt != null) insertStmt.close();
                if (conn != null) conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnsimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbobot;
    private javax.swing.JButton btnkeluar1;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnproses;
    private javax.swing.JButton btnproses1;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbdatanilai;
    private javax.swing.JTable tbdatapelanggan;
    private javax.swing.JTable tbperingkat;
    private javax.swing.JTextField txtpdt;
    private javax.swing.JTextField txtrwt;
    private javax.swing.JTextField txttg;
    private javax.swing.JTextField txtusia;
    // End of variables declaration//GEN-END:variables
}
