/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formtk;

import javax.swing.JFrame;

/**
 *
 * @author ASUS
 */
public class Form_Utama1 extends javax.swing.JFrame {

    /**
     * Creates new form Form_Utama
     */
    public Form_Utama1() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panel_menu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDataKriteria = new javax.swing.JButton();
        btnNilaiKriteria = new javax.swing.JButton();
        btnhasil = new javax.swing.JButton();
        btndatapelanggan = new javax.swing.JButton();
        btnkeluar1 = new javax.swing.JButton();
        panel_footer = new javax.swing.JPanel();
        panel_body = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_header.setBackground(new java.awt.Color(204, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("pada TK Islam Rabbani ");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sistem pendukung keputusan siswa berprestasi ");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logotkkecil.png"))); // NOI18N

        javax.swing.GroupLayout panel_headerLayout = new javax.swing.GroupLayout(panel_header);
        panel_header.setLayout(panel_headerLayout);
        panel_headerLayout.setHorizontalGroup(
            panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_headerLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addGroup(panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_headerLayout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_headerLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        panel_headerLayout.setVerticalGroup(
            panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_headerLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_headerLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        panel_menu.setBackground(new java.awt.Color(204, 0, 0));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnDataKriteria.setBackground(new java.awt.Color(102, 102, 102));
        btnDataKriteria.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        btnDataKriteria.setForeground(new java.awt.Color(255, 255, 255));
        btnDataKriteria.setText("Data Kriteria");
        btnDataKriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataKriteriaActionPerformed(evt);
            }
        });

        btnNilaiKriteria.setBackground(new java.awt.Color(102, 102, 102));
        btnNilaiKriteria.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        btnNilaiKriteria.setForeground(new java.awt.Color(255, 255, 255));
        btnNilaiKriteria.setText("Data Nilai Kriteria");
        btnNilaiKriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNilaiKriteriaActionPerformed(evt);
            }
        });

        btnhasil.setBackground(new java.awt.Color(102, 102, 102));
        btnhasil.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        btnhasil.setForeground(new java.awt.Color(255, 255, 255));
        btnhasil.setText("Data Hasil SAW");
        btnhasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhasilActionPerformed(evt);
            }
        });

        btndatapelanggan.setBackground(new java.awt.Color(102, 102, 102));
        btndatapelanggan.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        btndatapelanggan.setForeground(new java.awt.Color(255, 255, 255));
        btndatapelanggan.setText("Data Siswa");
        btndatapelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndatapelangganActionPerformed(evt);
            }
        });

        btnkeluar1.setBackground(new java.awt.Color(102, 102, 102));
        btnkeluar1.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        btnkeluar1.setForeground(new java.awt.Color(255, 255, 255));
        btnkeluar1.setText("Log Out (Keluar)");
        btnkeluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_menuLayout = new javax.swing.GroupLayout(panel_menu);
        panel_menu.setLayout(panel_menuLayout);
        panel_menuLayout.setHorizontalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_menuLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnhasil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNilaiKriteria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(btnDataKriteria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndatapelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnkeluar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_menuLayout.setVerticalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menuLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btndatapelanggan)
                .addGap(8, 8, 8)
                .addComponent(btnDataKriteria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNilaiKriteria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnhasil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 407, Short.MAX_VALUE)
                .addComponent(btnkeluar1)
                .addContainerGap())
        );

        panel_footer.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout panel_footerLayout = new javax.swing.GroupLayout(panel_footer);
        panel_footer.setLayout(panel_footerLayout);
        panel_footerLayout.setHorizontalGroup(
            panel_footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_footerLayout.setVerticalGroup(
            panel_footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        panel_body.setBackground(new java.awt.Color(204, 204, 204));
        panel_body.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout panel_bodyLayout = new javax.swing.GroupLayout(panel_body);
        panel_body.setLayout(panel_bodyLayout);
        panel_bodyLayout.setHorizontalGroup(
            panel_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_bodyLayout.setVerticalGroup(
            panel_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_body))
            .addComponent(panel_footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_body)
                    .addComponent(panel_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNilaiKriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNilaiKriteriaActionPerformed
         Form_InputNilaiKriteria frinik = new Form_InputNilaiKriteria();
        panel_body.removeAll();
        panel_body.add(frinik);
        frinik.setSize(panel_body.getWidth(), panel_body.getHeight());
        frinik.setVisible(true);
    }//GEN-LAST:event_btnNilaiKriteriaActionPerformed

    private void btnhasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhasilActionPerformed
        Form_DataHasilSAW fh = new Form_DataHasilSAW();
      panel_body.removeAll();
      panel_body.add(fh);
      fh.setSize(panel_body.getWidth(), panel_body.getHeight());
       fh.setVisible(true);
      //Form_DataHasilSAW fh = new Form_DataHasilSAW();
      //  fh.setVisible(true);
    }//GEN-LAST:event_btnhasilActionPerformed

    private void btnDataKriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataKriteriaActionPerformed
        Form_DataKriteria dk = new Form_DataKriteria();
        panel_body.removeAll();
        panel_body.add(dk);
        dk.setSize(panel_body.getWidth(), panel_body.getHeight());
        dk.setVisible(true);
    }//GEN-LAST:event_btnDataKriteriaActionPerformed

    private void btndatapelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndatapelangganActionPerformed
        // TODO add your handling code here:
        Form_Inputsiswa pl = new Form_Inputsiswa();
        panel_body.removeAll();
        panel_body.add(pl);
        pl.setSize(panel_body.getWidth(), panel_body.getHeight());
        pl.setVisible(true);
    }//GEN-LAST:event_btndatapelangganActionPerformed

    private void btnkeluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluar1ActionPerformed
        // TODO add your handling code here:
        dispose();
        Form_Login1 fl = new Form_Login1();
        fl.setVisible(true);
    }//GEN-LAST:event_btnkeluar1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDataKriteria;
    private javax.swing.JButton btnNilaiKriteria;
    private javax.swing.JButton btndatapelanggan;
    private javax.swing.JButton btnhasil;
    private javax.swing.JButton btnkeluar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDesktopPane panel_body;
    private javax.swing.JPanel panel_footer;
    private javax.swing.JPanel panel_header;
    private javax.swing.JPanel panel_menu;
    // End of variables declaration//GEN-END:variables
}
