/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formtk;

import formtk.KoneksiDB;
import java.beans.Statement;
import java.io.File;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author ASUS
 */
public class Form_DataKriteria extends javax.swing.JInternalFrame {
        /**
     * Creates new form Form_Data_Barang
     */
    
       
    public Form_DataKriteria() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).setNorthPane(null);
        ViewData();
        LebarKolom();
        Locale locale = new Locale("id","ID");
        Locale.setDefault(locale);
    }
    
    private void LebarKolom(){
        TableColumn column;
        tbdatakriteria.getColumnModel().getColumn(0).setPreferredWidth(100);
        tbdatakriteria.getColumnModel().getColumn(1).setPreferredWidth(100);
        tbdatakriteria.getColumnModel().getColumn(2).setPreferredWidth(100); 
    }
    
    private void ViewData(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Id Kriteria");
        tbl.addColumn("Nama Kriteria");
        tbl.addColumn("Bobot");
        tbdatakriteria.setModel(tbl);
        LebarKolom();
        try {
           com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement)KoneksiDB.getConnection().createStatement();
           ResultSet rs = statement.executeQuery("select * from kriteria");
           while(rs.next()){
               tbl.addRow(new Object[]{
                   rs.getString("IDKriteria"),
                   rs.getString("NamaKriteria"),
                   rs.getString("Bobot"),
               });
               tbdatakriteria.setModel(tbl);
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Gagal");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnsimpan = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdatakriteria = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdkriteria = new javax.swing.JTextField();
        txtnamakriteria = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtbobot = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnkeluar1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        btnsimpan.setBackground(new java.awt.Color(102, 102, 102));
        btnsimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnsimpan.setText("Simpan");
        btnsimpan.setPreferredSize(new java.awt.Dimension(109, 29));
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnedit.setBackground(new java.awt.Color(102, 102, 102));
        btnedit.setForeground(new java.awt.Color(255, 255, 255));
        btnedit.setText("Edit");
        btnedit.setPreferredSize(new java.awt.Dimension(109, 29));
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnhapus.setBackground(new java.awt.Color(102, 102, 102));
        btnhapus.setForeground(new java.awt.Color(255, 255, 255));
        btnhapus.setText("Hapus");
        btnhapus.setPreferredSize(new java.awt.Dimension(109, 29));
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        tbdatakriteria.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        tbdatakriteria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tbdatakriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdatakriteriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbdatakriteria);

        jLabel3.setBackground(new java.awt.Color(255, 0, 0));
        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Kriteria");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Form ini dugunakan untuk input data kriteria");

        jLabel5.setText("ID Kriteria");

        txtIdkriteria.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel6.setText("Nama Kriteria");

        jLabel7.setText("Bobot");

        btnkeluar1.setBackground(new java.awt.Color(102, 102, 102));
        btnkeluar1.setForeground(new java.awt.Color(255, 255, 255));
        btnkeluar1.setText("Keluar");
        btnkeluar1.setPreferredSize(new java.awt.Dimension(109, 29));
        btnkeluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluar1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cetak");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 441, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(42, 42, 42)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtbobot, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                            .addComponent(txtIdkriteria)
                                            .addComponent(txtnamakriteria)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                                        .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(btnkeluar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtIdkriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtnamakriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtbobot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnkeluar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        if(txtIdkriteria.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "ID Kriteria Kosong");
        }else if(txtnamakriteria.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Nama Kriteria Kosong");
        }else if(txtbobot.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Bobot Kosong");
        }else{
            String vIdKriteria = String.valueOf(txtIdkriteria.getText());
            String vNamaKriteria = String.valueOf(txtnamakriteria.getText());
            String vBobot = String.valueOf(txtbobot.getText());
            try {
                com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement)KoneksiDB.getConnection().createStatement();
                statement.executeUpdate("insert into kriteria (IDKriteria,NamaKriteria,bobot)"
                        + "values ('"+vIdKriteria+"','"+vNamaKriteria+"','"+vBobot+"')");
                statement.close();
                JOptionPane.showMessageDialog(null, "Data Tersimpan");
                txtIdkriteria.setText("");
                txtnamakriteria.setText("");
                txtbobot.setText("");
                txtIdkriteria.requestFocus();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Tidak Tersimpan");
            }
        }
        LebarKolom();
        ViewData();
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        if(txtIdkriteria.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "ID Pelanggan Kosong");
        }else if(txtnamakriteria.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Nama Kosong");
        }else if(txtbobot.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Bobot Kosong");
        }else{
            String vIdKriteria = String.valueOf(txtIdkriteria.getText());
            String vNamaKriteria = String.valueOf(txtnamakriteria.getText());
            String vBobot = String.valueOf(txtbobot.getText());
            try {
                com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement)KoneksiDB.getConnection().createStatement();
                statement.executeUpdate("update kriteria set NamaKriteria = '"+vNamaKriteria+"',bobot = '"+vBobot+"'"
                        + "where IDKriteria = '"+vIdKriteria+"'");
                statement.close();
                JOptionPane.showMessageDialog(null, "Data Tersimpan");
                txtIdkriteria.setText("");
                txtnamakriteria.setText("");
                txtbobot.setText("");
                txtIdkriteria.requestFocus();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Tidak Tersimpan");
            }
        }
        ViewData();
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        int pesan = JOptionPane.showConfirmDialog(null, "Hapus Data", "Konfirmasi",JOptionPane.YES_NO_OPTION);
        if(pesan==0){
            int row = tbdatakriteria.getSelectedRow();
            String id = tbdatakriteria.getValueAt(row, 0).toString();
            try {
                //Statement statement = (Statement)KoneksiDB.getConnection().createStatement();
                com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement)KoneksiDB.getConnection().createStatement();
                statement.executeUpdate("delete from kriteria where IDKriteria = '"+id+"'");
                statement.close();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                ViewData();
                LebarKolom();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Tidak Berhasil Dihapus");
            }
        }
        ViewData();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void tbdatakriteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdatakriteriaMouseClicked
        int row = tbdatakriteria.getSelectedRow();
        txtIdkriteria.setText(tbdatakriteria.getModel().getValueAt(row, 0).toString());
        txtnamakriteria.setText(tbdatakriteria.getModel().getValueAt(row, 1).toString());
        txtbobot.setText(tbdatakriteria.getModel().getValueAt(row, 2).toString());
    }//GEN-LAST:event_tbdatakriteriaMouseClicked

    private void btnkeluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnkeluar1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          try {
            String file = "src/formtk/kriteria.jasper";
            HashMap parameter = new HashMap();
            File reportFile = new File(file);
            JasperReport jsr = (JasperReport) JRLoader.loadObject(null, reportFile);
            JasperPrint jsp = JasperFillManager.fillReport(jsr, parameter, KoneksiDB.getConnection());
            JasperViewer.viewReport(jsp,false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar1;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbdatakriteria;
    private javax.swing.JTextField txtIdkriteria;
    private javax.swing.JTextField txtbobot;
    private javax.swing.JTextField txtnamakriteria;
    // End of variables declaration//GEN-END:variables
}
