/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formtk;

import formtk.KoneksiDB;
import java.beans.Statement;
import java.io.File;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author ASUS
 */
public class Form_Inputsiswa extends javax.swing.JInternalFrame {
        /**
     * Creates new form Form_Data_Barang
     */
    
       
    public Form_Inputsiswa() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).setNorthPane(null);
        ViewData();
        LebarKolom();
        Locale locale = new Locale("id","ID");
        Locale.setDefault(locale);
    }
    
    private void LebarKolom(){
        TableColumn column;
        tbdatapelanggan.getColumnModel().getColumn(0).setPreferredWidth(100);
        tbdatapelanggan.getColumnModel().getColumn(1).setPreferredWidth(100);
        tbdatapelanggan.getColumnModel().getColumn(2).setPreferredWidth(100); 
        tbdatapelanggan.getColumnModel().getColumn(3).setPreferredWidth(100); 
    }
    
    private void ViewData(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Id ");
        tbl.addColumn("Nama");
        tbl.addColumn("Usia");
        tbl.addColumn("Alamat");
        tbdatapelanggan.setModel(tbl);
        LebarKolom();
        try {
           com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement)KoneksiDB.getConnection().createStatement();
           ResultSet rs = statement.executeQuery("select * from datamobil");
           while(rs.next()){
               tbl.addRow(new Object[]{
                   rs.getString("idmobil"),
                   rs.getString("merk"),
                   rs.getString("usiamobil"),
                   rs.getString("noRangka"),
               });
               tbdatapelanggan.setModel(tbl);
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Gagal");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnsimpan = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdatapelanggan = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdpelanggan = new javax.swing.JTextField();
        txtnamapelnggan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtnmrtel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnkeluar1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtalamat = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel1.setBackground(new java.awt.Color(255, 102, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        btnsimpan.setBackground(new java.awt.Color(102, 102, 102));
        btnsimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnsimpan.setText("Simpan");
        btnsimpan.setPreferredSize(new java.awt.Dimension(109, 29));
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnedit.setBackground(new java.awt.Color(102, 102, 102));
        btnedit.setForeground(new java.awt.Color(255, 255, 255));
        btnedit.setText("Edit");
        btnedit.setPreferredSize(new java.awt.Dimension(109, 29));
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnhapus.setBackground(new java.awt.Color(102, 102, 102));
        btnhapus.setForeground(new java.awt.Color(255, 255, 255));
        btnhapus.setText("Hapus");
        btnhapus.setPreferredSize(new java.awt.Dimension(109, 29));
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnprint.setBackground(new java.awt.Color(102, 102, 102));
        btnprint.setForeground(new java.awt.Color(255, 255, 255));
        btnprint.setText("Cetak");
        btnprint.setPreferredSize(new java.awt.Dimension(109, 29));
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        tbdatapelanggan.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        tbdatapelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "null"
            }
        ));
        tbdatapelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdatapelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbdatapelanggan);

        jLabel3.setBackground(new java.awt.Color(255, 0, 0));
        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("Data Siswa");

        jLabel5.setText("ID Siswa");

        txtIdpelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel6.setText("Nama");

        jLabel7.setText("Usia ");

        btnkeluar1.setBackground(new java.awt.Color(102, 102, 102));
        btnkeluar1.setForeground(new java.awt.Color(255, 255, 255));
        btnkeluar1.setText("Keluar");
        btnkeluar1.setPreferredSize(new java.awt.Dimension(109, 29));
        btnkeluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluar1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Alamat");

        txtalamat.setColumns(20);
        txtalamat.setRows(5);
        jScrollPane2.setViewportView(txtalamat);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnkeluar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnprint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnmrtel, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(txtIdpelanggan)
                            .addComponent(txtnamapelnggan)
                            .addComponent(jScrollPane2))))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtIdpelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtnamapelnggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtnmrtel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnprint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnkeluar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        if(txtIdpelanggan.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "ID Mobil Kosong");
        }else if(txtnamapelnggan.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Merk Kosong");
        }else if(txtnmrtel.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Usia Mobil Kosong");
        }else if(txtalamat.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "No Rangka Kosong");
        }else{
            String vIdPelanggan = String.valueOf(txtIdpelanggan.getText());
            String vNama = String.valueOf(txtnamapelnggan.getText());
            String vNoTel = String.valueOf(txtnmrtel.getText());
            String vAlamat = String.valueOf(txtalamat.getText());
            try {
                com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement)KoneksiDB.getConnection().createStatement();
                statement.executeUpdate("insert into datamobil (idmobil,merk,usiamobil,noRangka)"
                        + "values ('"+vIdPelanggan+"','"+vNama+"','"+vNoTel+"','"+vAlamat+"')");
                statement.close();
                JOptionPane.showMessageDialog(null, "Data Tersimpan");
                txtIdpelanggan.setText("");
                txtnamapelnggan.setText("");
                txtnmrtel.setText("");
                txtalamat.setText("");
                txtIdpelanggan.requestFocus();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Tidak Tersimpan");
            }
        }
        LebarKolom();
        ViewData();
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        try {
            String file = "src/formtk/datasis.jasper";
            HashMap parameter = new HashMap();
            File reportFile = new File(file);
            JasperReport jsr = (JasperReport) JRLoader.loadObject(null, reportFile);
            JasperPrint jsp = JasperFillManager.fillReport(jsr, parameter, KoneksiDB.getConnection());
            JasperViewer.viewReport(jsp,false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnprintActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        if(txtIdpelanggan.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "ID Mobil Kosong");
        }else if(txtnamapelnggan.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Merk Kosong");
        }else if(txtnmrtel.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Usia Kosong");
        }else if(txtalamat.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "No Rangka Kosong");
        }else{
            String vIdPelanggan = String.valueOf(txtIdpelanggan.getText());
            String vNama = String.valueOf(txtnamapelnggan.getText());
            String vNoTel = String.valueOf(txtnmrtel.getText());
            String vAlamat = String.valueOf(txtalamat.getText());
            try {
                com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement)KoneksiDB.getConnection().createStatement();
                statement.executeUpdate("update datamobil set merk = '"+vNama+"',usiamobil = '"+vNoTel+"',noRangka = '"+vAlamat+"'"
                        + "where idmobil = '"+vIdPelanggan+"'");
                statement.close();
                JOptionPane.showMessageDialog(null, "Data Tersimpan");
                txtIdpelanggan.setText("");
                txtnamapelnggan.setText("");
                txtnmrtel.setText("");
                txtalamat.setText("");
                txtIdpelanggan.requestFocus();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Tidak Tersimpan");
            }
        }
        ViewData();
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        int pesan = JOptionPane.showConfirmDialog(null, "Hapus Data", "Konfirmasi",JOptionPane.YES_NO_OPTION);
        if(pesan==0){
            int row = tbdatapelanggan.getSelectedRow();
            String id = tbdatapelanggan.getValueAt(row, 0).toString();
            try {
                //Statement statement = (Statement)KoneksiDB.getConnection().createStatement();
                com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement)KoneksiDB.getConnection().createStatement();
                statement.executeUpdate("delete from datamobil where idmobil = '"+id+"'");
                statement.close();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                ViewData();
                LebarKolom();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Tidak Berhasil Dihapus");
            }
        }
        ViewData();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void tbdatapelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdatapelangganMouseClicked
        int row = tbdatapelanggan.getSelectedRow();
        txtIdpelanggan.setText(tbdatapelanggan.getModel().getValueAt(row, 0).toString());
        txtnamapelnggan.setText(tbdatapelanggan.getModel().getValueAt(row, 1).toString());
        txtnmrtel.setText(tbdatapelanggan.getModel().getValueAt(row, 2).toString());
        txtalamat.setText(tbdatapelanggan.getModel().getValueAt(row, 3).toString());
    }//GEN-LAST:event_tbdatapelangganMouseClicked

    private void btnkeluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnkeluar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar1;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbdatapelanggan;
    private javax.swing.JTextField txtIdpelanggan;
    private javax.swing.JTextArea txtalamat;
    private javax.swing.JTextField txtnamapelnggan;
    private javax.swing.JTextField txtnmrtel;
    // End of variables declaration//GEN-END:variables
}
