/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formtk;

import java.awt.event.KeyEvent;
import formtk.KoneksiDB;
import java.beans.Statement;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author ASUS
 */
public class Form_InputNilaiKriteria extends javax.swing.JInternalFrame {
        /**
     * Creates new form Form_Data_Barang
     */
    
     
    public Form_InputNilaiKriteria() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).setNorthPane(null);
        ViewData();
        LebarKolom();
        Locale locale = new Locale("id","ID");
        Locale.setDefault(locale);
    }
    
    private void LebarKolom(){
        TableColumn column;
        tbdatapelanggan.getColumnModel().getColumn(0).setPreferredWidth(100);
        tbdatapelanggan.getColumnModel().getColumn(1).setPreferredWidth(100);
        tbdatapelanggan.getColumnModel().getColumn(2).setPreferredWidth(100); 
        tbdatapelanggan.getColumnModel().getColumn(3).setPreferredWidth(100); 
        tbdatapelanggan.getColumnModel().getColumn(4).setPreferredWidth(100);
        tbdatapelanggan.getColumnModel().getColumn(5).setPreferredWidth(100); 
        tbdatapelanggan.getColumnModel().getColumn(6).setPreferredWidth(100); 
    }
    
    private void ViewData(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("ID Nilai Kriteria");
        tbl.addColumn("ID Siswa");
        tbl.addColumn("Nama");
        tbl.addColumn("Absensi");
        tbl.addColumn("Nilai Akademik");
        tbl.addColumn("Nilai Keterampilan");
        tbl.addColumn("Indisipliner");
        tbdatapelanggan.setModel(tbl);
        LebarKolom();
        try {
           com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement)KoneksiDB.getConnection().createStatement();
           ResultSet rs = statement.executeQuery("select * from nilaikriteria");
           while(rs.next()){
               tbl.addRow(new Object[]{
                   rs.getString("IDNilaiKriteria"),
                   rs.getString("IDmobil"),
                   rs.getString("merk"),
                   rs.getString("jarak"),
                   rs.getString("harga"),
                   rs.getString("usiamobil"),
                   rs.getString("bbm"),
               });
               tbdatapelanggan.setModel(tbl);
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Gagal");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnsimpan = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdatapelanggan = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdnilai = new javax.swing.JTextField();
        txtidpelnggan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtnmplg = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnkeluar1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtusia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtpendapatan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txttanggungan = new javax.swing.JTextField();
        jCRKredit = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        btnsimpan.setBackground(new java.awt.Color(102, 102, 102));
        btnsimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnsimpan.setText("Simpan");
        btnsimpan.setPreferredSize(new java.awt.Dimension(109, 29));
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnedit.setBackground(new java.awt.Color(102, 102, 102));
        btnedit.setForeground(new java.awt.Color(255, 255, 255));
        btnedit.setText("Edit");
        btnedit.setPreferredSize(new java.awt.Dimension(109, 29));
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnhapus.setBackground(new java.awt.Color(102, 102, 102));
        btnhapus.setForeground(new java.awt.Color(255, 255, 255));
        btnhapus.setText("Hapus");
        btnhapus.setPreferredSize(new java.awt.Dimension(109, 29));
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        tbdatapelanggan.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        tbdatapelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "null", "Title 5", "Title 6", "Title 7"
            }
        ));
        tbdatapelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdatapelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbdatapelanggan);

        jLabel3.setBackground(new java.awt.Color(255, 0, 0));
        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("Input Nilai Kriteria");

        jLabel4.setText("Form ini dugunakan untuk input nilai kriteria");

        jLabel5.setText("ID Nilai Kriteria");

        txtIdnilai.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtidpelnggan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidpelngganKeyPressed(evt);
            }
        });

        jLabel6.setText("ID Siswa");

        jLabel7.setText("Nama");

        btnkeluar1.setBackground(new java.awt.Color(102, 102, 102));
        btnkeluar1.setForeground(new java.awt.Color(255, 255, 255));
        btnkeluar1.setText("Keluar");
        btnkeluar1.setPreferredSize(new java.awt.Dimension(109, 29));
        btnkeluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluar1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Absensi");

        jLabel9.setText("Nilai Akademik");

        jLabel10.setText("Nilai Keterampilan");

        jLabel11.setText("Indisipliner");

        jCRKredit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        jCRKredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCRKreditActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cetak");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnkeluar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnhapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCRKredit, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttanggungan, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtnmplg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtIdnilai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtidpelnggan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtusia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addGap(15, 15, 15)
                                .addComponent(jLabel9)
                                .addGap(15, 15, 15)
                                .addComponent(jLabel10)
                                .addGap(15, 15, 15)
                                .addComponent(jLabel11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtIdnilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtidpelnggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnmplg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtusia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(txtpendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCRKredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttanggungan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnkeluar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed

           
        if(txtIdnilai.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "ID Nilai Kosong");
        }else if(txtidpelnggan.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "ID Mobil Kosong");
        }else if(txtnmplg.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Merk Kosong");
        }else if(txtusia.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Jarak Kosong");
        }else if(txtpendapatan.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Harga Kosong");
        }else if(jCRKredit.getSelectedItem().equals("pilih")){
            JOptionPane.showMessageDialog(null, "Anda belum memilih usia mobil");
        }else if(txttanggungan.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Konsumsi BBM Kosong");
        }else{
            String vIdNilai = String.valueOf(txtIdnilai.getText());
            String vIdPelanggan = String.valueOf(txtidpelnggan.getText());
            String vNama = String.valueOf(txtnmplg.getText());
            String vUsia = String.valueOf(txtusia.getText());
            String vPendapatan = String.valueOf(txtpendapatan.getText());
            String vTanggungan = String.valueOf(txttanggungan.getText());
            try {
                com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement)KoneksiDB.getConnection().createStatement();
                statement.executeUpdate("insert into nilaikriteria (IDNilaiKriteria,IDmobil,merk, jarak,harga,usiamobil,bbm)"
                        + "values ('"+vIdNilai+"','"+vIdPelanggan+"','"+vNama+"','"+vUsia+"','"+vPendapatan+"','"+jCRKredit.getSelectedItem().toString()+"','"+vTanggungan+"')");
                statement.close();
                JOptionPane.showMessageDialog(null, "Data Tersimpan");
                txtIdnilai.setText("");
                txtidpelnggan.setText("");
                txtnmplg.setText("");
                txtusia.setText("");
                txtpendapatan.setText("");
                txttanggungan.setText("");
                txtIdnilai.requestFocus();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Tidak Tersimpan");
            }
        }
        LebarKolom();
        ViewData();
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        if(txtIdnilai.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "ID Nilai Kosong");
        }else if(txtidpelnggan.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "ID Mobil Kosong");
        }else if(txtnmplg.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Merk Kosong");
        }else if(txtusia.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Jarak Kosong");
        }else if(txtpendapatan.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Harga Kosong");
        }else if(jCRKredit.getSelectedItem().equals("pilih")){
            JOptionPane.showMessageDialog(null, "Anda belum memilih Usia Mobil");
        }else if(txttanggungan.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Konsumsi BBM Kosong");
        }else{
            String vIdNilai = String.valueOf(txtIdnilai.getText());
            String vIdPelanggan = String.valueOf(txtidpelnggan.getText());
            String vNama = String.valueOf(txtnmplg.getText());
            String vUsia = String.valueOf(txtusia.getText());
            String vPendapatan = String.valueOf(txtpendapatan.getText());
            String vTanggungan = String.valueOf(txttanggungan.getText());
            try {
                com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement)KoneksiDB.getConnection().createStatement();
                statement.executeUpdate("update nilaikriteria set IDmobil = '"+vIdPelanggan+"',merk = '"+vNama+"',jarak = '"+vUsia+"',"
                        + "harga = '"+vPendapatan+"',usiamobil = '"+jCRKredit.getSelectedItem().toString()+"',bbm = '"+vTanggungan+"'"
                        + " where IDNilaiKriteria = '"+vIdNilai+"'");
                statement.close();
                JOptionPane.showMessageDialog(null, "Data Tersimpan");
               txtIdnilai.setText("");
                txtidpelnggan.setText("");
                txtnmplg.setText("");
                txtusia.setText("");
                txtpendapatan.setText("");
                txttanggungan.setText("");
                txtIdnilai.requestFocus();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Tidak Tersimpan");
            }
        }
        ViewData();
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        int pesan = JOptionPane.showConfirmDialog(null, "Hapus Data", "Konfirmasi",JOptionPane.YES_NO_OPTION);
        if(pesan==0){
            int row = tbdatapelanggan.getSelectedRow();
            String id = tbdatapelanggan.getValueAt(row, 0).toString();
            try {
                //Statement statement = (Statement)KoneksiDB.getConnection().createStatement();
                com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement)KoneksiDB.getConnection().createStatement();
                statement.executeUpdate("delete from nilaikriteria where IDNilaiKriteria = '"+id+"'");
                statement.close();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                ViewData();
                LebarKolom();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Tidak Berhasil Dihapus");
            }
        }
        ViewData();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void tbdatapelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdatapelangganMouseClicked
        int row = tbdatapelanggan.getSelectedRow();
        txtIdnilai.setText(tbdatapelanggan.getModel().getValueAt(row, 0).toString());
        txtidpelnggan.setText(tbdatapelanggan.getModel().getValueAt(row, 1).toString());
        txtnmplg.setText(tbdatapelanggan.getModel().getValueAt(row, 2).toString());
        txtusia.setText(tbdatapelanggan.getModel().getValueAt(row, 3).toString());
        txtpendapatan.setText(tbdatapelanggan.getModel().getValueAt(row, 4).toString());
        txttanggungan.setText(tbdatapelanggan.getModel().getValueAt(row, 6).toString());
    }//GEN-LAST:event_tbdatapelangganMouseClicked

    private void btnkeluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnkeluar1ActionPerformed

    private void txtidpelngganKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidpelngganKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                txtusia.requestFocus();
                com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement)KoneksiDB.getConnection().createStatement();
                ResultSet rs = statement.executeQuery("select * from datamobil where IDmobil like '%"+txtnmplg.getText()+"%'");
                while(rs.next()){
                    txtnmplg.setText(rs.getString("merk"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(Form_InputNilaiKriteria.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtidpelngganKeyPressed

    private void jCRKreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCRKreditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCRKreditActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  try {
            String file = "src/formtk/nilaikriteria.jasper";
            HashMap parameter = new HashMap();
            File reportFile = new File(file);
            JasperReport jsr = (JasperReport) JRLoader.loadObject(null, reportFile);
            JasperPrint jsp = JasperFillManager.fillReport(jsr, parameter, KoneksiDB.getConnection());
            JasperViewer.viewReport(jsp,false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar1;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jCRKredit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbdatapelanggan;
    private javax.swing.JTextField txtIdnilai;
    private javax.swing.JTextField txtidpelnggan;
    private javax.swing.JTextField txtnmplg;
    private javax.swing.JTextField txtpendapatan;
    private javax.swing.JTextField txttanggungan;
    private javax.swing.JTextField txtusia;
    // End of variables declaration//GEN-END:variables
}
